### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by domenkozar** [domenkozar/proxsign-nix#2]
Mention in readme that:

```
$ nix-shell -p bash --pure --run "/home/ielectric/.nix-profile/bin/proxsign"
```

resolves the issue, it's probably some environment variables.

**Comment by silverhook** [comment]
Does not work when installed on NixOS through `/etc/nixos/configuration.nix`

**Comment by domenkozar** [comment]
yeah did you try using the workaround?

**Comment by silverhook** [comment]
Yup. That’s what I’m saying – the workaround only works if it’s installed with `nix-env -install`.

**Comment by domenkozar** [comment]
This is fixed now, at least I can't reproduce.
